# Generated by Django 4.2.15 on 2024-08-14 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_category_rename_suptitle_article_subtitle_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='article',
            new_name='articles_title_e14a16_idx',
            old_name='home_articl_title_2b6ae8_idx',
        ),
        migrations.AlterModelTable(
            name='article',
            table='articles',
        ),
    ]
